apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::162870366695:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Q8LYHI2UTTHC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::162870366695:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-12T01:14:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2805"
  uid: cb65d5af-f5c0-457c-96da-4b564b69708a
